/* vim: set ts=8 sts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * sanitize a document fragment in-place
 * @param {object} config - configuration of the sanitizer object
 * @param {Node} input - a document fragment
 * @return Nothing - the operation is in-place
 */
export const sanitizeDocFragment = function _sanitizeDocFragment(
  config,
  input
) {
  let normalizedConfig = _normalizeConfig(config);
  normalizedConfig.IN_PLACE = true;
  DOMPurify.sanitize(input, normalizedConfig);
};

/**
 * normalize a supplied Sanitizer-API config, to ensure baseline safety
 * @param config
 * @return {object} - a secure config
 * @private
 */
export const _normalizeConfig = function _normalizeConfig(config) {
  if (!config) {
    config = {};
  }
  const allowElements = config.allowElements || DEFAULT_ALLOWED_ELEMENTS;
  const allowAttributes = config.allowAttributes || DEFAULT_ALLOWED_ATTRIBUTES;
  const blockElements = config.blockElements || DEFAULT_BLOCKED_ELEMENTS;
  const dropElements = config.dropElements || DEFAULT_DROP_ELEMENTS;
  const dropAttributes = config.dropAttributes || DEFAULT_DROP_ATTRIBUTES;
  const allowComments = !!config.allowComments;
  const allowCustomElements = !!config.allowCustomElements;
  return {
    allowElements,
    allowAttributes,
    blockElements,
    dropElements,
    dropAttributes,
    allowCustomElements,
    allowComments,
  };
};

/**
 * transform a Sanitizer-API-shaped configuration object into a config for DOMPurify invocation
 * @param config
 * @return {object} - a DOMPurify-compatible configuration object
 * @private
 */
export const _transformConfig = function transformConfig(config) {
  const allowElems = config.allowElements || [];
  const allowAttrs = config.allowAttributes || [];
  const dropElems = config.dropElements || [];
  const dropAttrs = config.dropAttributes || [];
  return {
    ALLOWED_TAGS: allowElems,
    ALLOWED_ATTR: allowAttrs,
    FORBID_TAGS: dropElems,
    FORBID_ATTR: dropAttrs,
  };
};

// from https://wicg.github.io/sanitizer-api/#constants
const DEFAULT_ALLOWED_ELEMENTS = [
  "a",
  "abbr",
  "acronym",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "basefont",
  "bdi",
  "bdo",
  "bgsound",
  "big",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "center",
  "cite",
  "code",
  "col",
  "colgroup",
  "command",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "dir",
  "div",
  "dl",
  "dt",
  "em",
  "fieldset",
  "figcaption",
  "figure",
  "font",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "image",
  "img",
  "input",
  "ins",
  "kbd",
  "keygen",
  "label",
  "layer",
  "legend",
  "li",
  "link",
  "listing",
  "main",
  "map",
  "mark",
  "marquee",
  "menu",
  "meta",
  "meter",
  "nav",
  "nobr",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "picture",
  "plaintext",
  "popup",
  "portal",
  "pre",
  "progress",
  "q",
  "rb",
  "rp",
  "rt",
  "rtc",
  "ruby",
  "s",
  "samp",
  "section",
  "select",
  "selectmenu",
  "slot",
  "small",
  "source",
  "span",
  "strike",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "tt",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
];
const DEFAULT_ALLOWED_ATTRIBUTES = [
  "abbr",
  "accept",
  "accept-charset",
  "accesskey",
  "action",
  "align",
  "alink",
  "allow",
  "allowfullscreen",
  "allowpaymentrequest",
  "alt",
  "anchor",
  "archive",
  "as",
  "async",
  "autocapitalize",
  "autocomplete",
  "autocorrect",
  "autofocus",
  "autopictureinpicture",
  "autoplay",
  "axis",
  "background",
  "behavior",
  "bgcolor",
  "border",
  "bordercolor",
  "capture",
  "cellpadding",
  "cellspacing",
  "challenge",
  "char",
  "charoff",
  "charset",
  "checked",
  "cite",
  "class",
  "classid",
  "clear",
  "code",
  "codebase",
  "codetype",
  "color",
  "cols",
  "colspan",
  "compact",
  "content",
  "contenteditable",
  "controls",
  "controlslist",
  "conversiondestination",
  "coords",
  "crossorigin",
  "csp",
  "data",
  "datetime",
  "declare",
  "decoding",
  "default",
  "defer",
  "dir",
  "direction",
  "dirname",
  "disabled",
  "disablepictureinpicture",
  "disableremoteplayback",
  "disallowdocumentaccess",
  "download",
  "draggable",
  "elementtiming",
  "enctype",
  "end",
  "enterkeyhint",
  "event",
  "exportparts",
  "face",
  "for",
  "form",
  "formaction",
  "formenctype",
  "formmethod",
  "formnovalidate",
  "formtarget",
  "frame",
  "frameborder",
  "headers",
  "height",
  "hidden",
  "high",
  "href",
  "hreflang",
  "hreftranslate",
  "hspace",
  "http-equiv",
  "id",
  "imagesizes",
  "imagesrcset",
  "importance",
  "impressiondata",
  "impressionexpiry",
  "incremental",
  "inert",
  "inputmode",
  "integrity",
  "invisible",
  "is",
  "ismap",
  "keytype",
  "kind",
  "label",
  "lang",
  "language",
  "latencyhint",
  "leftmargin",
  "link",
  "list",
  "loading",
  "longdesc",
  "loop",
  "low",
  "lowsrc",
  "manifest",
  "marginheight",
  "marginwidth",
  "max",
  "maxlength",
  "mayscript",
  "media",
  "method",
  "min",
  "minlength",
  "multiple",
  "muted",
  "name",
  "nohref",
  "nomodule",
  "nonce",
  "noresize",
  "noshade",
  "novalidate",
  "nowrap",
  "object",
  "open",
  "optimum",
  "part",
  "pattern",
  "ping",
  "placeholder",
  "playsinline",
  "policy",
  "poster",
  "preload",
  "pseudo",
  "readonly",
  "referrerpolicy",
  "rel",
  "reportingorigin",
  "required",
  "resources",
  "rev",
  "reversed",
  "role",
  "rows",
  "rowspan",
  "rules",
  "sandbox",
  "scheme",
  "scope",
  "scopes",
  "scrollamount",
  "scrolldelay",
  "scrolling",
  "select",
  "selected",
  "shadowroot",
  "shadowrootdelegatesfocus",
  "shape",
  "size",
  "sizes",
  "slot",
  "span",
  "spellcheck",
  "src",
  "srcdoc",
  "srclang",
  "srcset",
  "standby",
  "start",
  "step",
  "style",
  "summary",
  "tabindex",
  "target",
  "text",
  "title",
  "topmargin",
  "translate",
  "truespeed",
  "trusttoken",
  "type",
  "usemap",
  "valign",
  "value",
  "valuetype",
  "version",
  "virtualkeyboardpolicy",
  "vlink",
  "vspace",
  "webkitdirectory",
  "width",
  "wrap",
];
const DEFAULT_BLOCKED_ELEMENTS = [
  "script",
  "iframe",
  "object",
  "embed",
  "param",
  "noscript",
  "noframes",
  "noembed",
  "nolayer",
  "base",
  "plaintext",
  "title",
  "textarea",
  "xmp",
  "basefont",
  "template",
  "slot",
  "portal",
  "data",
];
const DEFAULT_DROP_ELEMENTS = [];
const DEFAULT_DROP_ATTRIBUTES = [];
